version: "3.7"

services:
  xlsx2pdf-libre:
    build:
      context: ../src/
    image: holography/xlsx2pdf-libre-api:0.4.0
    ports:
     - "8070:8070"
    environment:
     - HOST=${HOST}
     - MARGIN=${MARGIN}
    healthcheck:
      test: "wget --spider ${HOST}/health"
      interval: 15s
      retries: 10
